id: seo_admin
permissions:
  - 'view all media revisions'
  - 'access files overview'
  - 'dropzone upload files'
  - 'access editor_media_browser entity browser pages'
  - 'access editor_multiple_image_browser entity browser pages'
  - 'access editor_multiple_media_browser entity browser pages'
  - 'access image_browser entity browser pages'
  - 'access media_browser entity browser pages'
  - 'access multiple_image_browser entity browser pages'
  - 'access multiple_media_browser entity browser pages'
  - 'access video_browser entity browser pages'
  - 'use media_bulk_upload bulk upload form'
